# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carlin Scott
email: carlin@carlinscott.com
tagline: A software development blog
description: >- # this means to ignore newlines until "baseurl:"
  Professional blog of Carlin Scott, a Senior Software Engineer working from the Silicon Forest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.carlinscott.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Carlin Scott
avatar: https://secure.gravatar.com/avatar/d4a11103f5b2b3a461f577bc08c546c0
google_analytics: G-SE1GDYXG06
gitlab_username: carlin.q.scott
stackoverflow_username: carlin-scott
twitter_username: carlinqscott
twitter:
  username: carlinqscott
github_username:  carlin-q-scott
linkedin_username: carlinqscott
mastodon:
  - username: carlin
    instance: freeradical.zone
disqus:
  shortname: carlinscott
show_excerpts: true

# Build settings
theme: minima #https://github.com/jekyll/minima/tree/2.5-stable
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
